### ISSUE TITLE
Failing since recent Chrome version

### ISSUE THREAD

**Issue by keithdtyler** [ksathyanm/find-chrome-version#87]
Since seemingly the recent Chrome update, this appears to be failing with the following error.

TypeError: Cannot read properties of null (reading '1')
    at module.exports (.../node_modules/find-chrome-version/index.js:43:38)

OS:MacOS Sonoma 14.6.1
Arch:M1
Chrome version: 128.0.6613.84

**Comment by sommerlilie** [comment]
I found a dirty fix. Chaning the regex to `const regExp = /Chrome\/(.*)/ ` resolves the issue. But I am not sure exactly how stable this is or why it works. I found no info about changes in the Version endpoint `json/version`.

**Comment by rajeshgithubs** [comment]
even me facing same issue.

where to change regex? can you pls advise. @sommerlilie 

const regExp = /Chrome\/(.*)/

**Comment by keithdtyler** [comment]
The module appears to launch a headless Chrome instance with remote-debug-port on, and use the debug port to make a request to retrieve a hunk of JSON.

Currently the "Browser" field of the JSON says "Chrome/128.0......" I'm guessing that previous versions said "HeadlessChrome" there since that is what the module is looking for.

@rajeshgithubs the line is in index.js, line 10

**Comment by ksathyanm** [comment]
@keithdtyler @sommerlilie @rajeshgithubs Please try the latest version `find-chrome-version@3`. Thank you.

**Comment by ksathyanm** [comment]
> @ksathyanm Can you still support node 16.x?

@matanm2 I just published 3.1.0 with Node 16 support.
